language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
install: 
- "pip install mf"
- "pip install git+https://github.com/mobyle2/mongokit@master#egg=mongokit"
- "pip install py-bcrypt mf pygeoip pairtree gitpython==0.3.2.RC1 python-ldap"
- "pip install git+https://github.com/mobyle2/mobyle2.lib.git@develop#egg=mobyle.lib"
- "pip install coverage"
- "pip install python-coveralls"
- "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
- "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: 
- python setup.py build
- python setup.py test -vv
- cd tests && coverage run --source ../mob2exec/mobyle/execution_engine run_tests.py && coverage html
after_success:
  - coveralls
