language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
install: 
- "pip install mongokit mf"
- "pip install coverage"
- "pip install python-coveralls"
- "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
- "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: 
- python setup.py build
- python setup.py test -vv
- cd tests && coverage run run_tests.py && coverage html
after_success:
  - coveralls
